#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## In case is running
./stop_box

## Update mustekala geth
## You must have done in the past
##   mkdir -p /home/core/mustekala-geth
##   git clone https://github.com/MetaMask/go-ethereum.git /home/core/mustekala-geth
cd /home/core/mustekala-geth
git checkout master
git pull

## Go back
cd $CURRENT_DIR

## Rebuild geth
docker run -ti --rm --name compile-geth \
	-v /home/core/mustekala-geth:/go/src/github.com/metamask/go-ethereum \
	-w /go/src/github.com/metamask/go-ethereum \
	golang:1.10.3 \
	make geth

## Start the container
./run_box
